markdown_extensions:
  - admonition
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - kroki:
      DownloadImages: true
      ServerURL: http://localhost:51080
      HttpMethod: POST
      FileTypes:
        - png
        - svg

site_name: "CZBioHub HPC User Quide"
site_url: "https://hpc.czbiohub.org/hpc-user-guide"
site_description: "CZBioHub HPC User Guide"
site_author: "@griznog"
dev_addr: "127.0.0.1:18080"
theme:
  name: material
  logo: assets/logo.svg
  palette:
    primary: custom
extra_css:
  - 'css/extra.css'


